### PR TITLE
Add deprecation warning and new location

### PR DESCRIPTION
**Pull request by cyphactor**
Why you made the change:

I did this so that people could easily discover the new official
repository.

### CODE REVIEW

**Comment by cyphactor** [comment]
@drujensen can you approve this PR? People are having a difficult time finding the official pra repository now.

**Comment by cyphactor** [comment]
Also, it would be ideal if we could get the homepage of the repository set to https://github.com/codebreakdown/pra.

I guess the most ideal would be to kill the reachlocal/pra repository to remove confusion. Is that a possibility?

**Comment by drujensen** [comment]
@cyphactor I noticed that there are several issues documented in the readme that point to the reach local repository.

Instead of killing it, what if I transfer ownership of the repository to codebreakdown?  I will need admin access to the code breakdown repository to do that.  I’m ok if its temporary just to transfer this over. Let me know if that works.

**Comment by cyphactor** [comment]
@drujensen technically you deleting the repository in reachlocal does the same thing because I already have a fork of it in codebreakdown.

**Comment by cyphactor** [comment]
although, we wouldn't get the issues. So, lets try and migrate it.

I added you to a team, let me know what it is. You can chat with my on Slack in the OC Ruby channel.

**Pull request merged**
